site_name: 'TRP Documentation'
site_description: 'Welcome to the TRP documentation'
site_author: 'TRP'
site_url: 'https://terra-isles-roleplay.github.io/trp-docs'
copyright: 'Copyright © 2024 Terra Isles Roleplay'
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - meta
  - codehilite
  - toc
  - footnotes
  - attr_list

plugins:
    - search

nav:
  - Home: 'index.md'
  - FiveM:
    - Version 1.0: 'fivem/1.0/index.md'
    - Version 2.0:
      - Home: 'fivem/2.0/index.md'
      - Get Started: 'fivem/2.0/start.md'
      - Changelog: 'fivem/2.0/changelog.md'
      - Commands: 
        - 'fivem/2.0/cmds/leo.md'
        - 'fivem/2.0/cmds/fire-ems.md'
        - 'fivem/2.0/cmds/civ.md'
      - Scripts:
        - Radio: 'fivem/2.0/scripts/radio.md'
      - Vehicles:
        - 'fivem/2.0/vehicles/leo.md'
        - 'fivem/2.0/vehicles/fire-ems.md'
        - 'fivem/2.0/vehicles/shared.md'
        - 'fivem/2.0/vehicles/civ.md'
    - Version 3.0:
      - Home: 'fivem/3.0/index.md'
      - Changelog: 'fivem/3.0/changelog.md'
  - CAD: 'cad-mdt/index.md'
  

