site_name: 'TRP Documentation'
site_description: 'Welcome to the TRP documentation'
site_author: 'TRP'
site_url: 'https://terra-isles-roleplay.github.io/trp-docs'
copyright: 'Copyright © 2024 Terra Isles Roleplay'
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - meta
  - codehilite
  - toc
  - footnotes
  - attr_list

plugins:
    - search

nav:
  - Home: 'index.md'
  - Version 1.0: '1.0/index.md'
  - Version 2.0:
    - Home: '2.0/index.md'
    - Get Started: '2.0/start.md'
    - Changelog: '2.0/changelog.md'
    - Commands: 
      - 'cmds/leo.md'
      - 'cmds/fire-ems.md'
      - 'cmds/civ.md'
    - Scripts:
      - Radio: 'scripts/radio.md'
    - Vehicles:
      - 'vehicles/leo.md'
      - 'vehicles/fire-ems.md'
      - 'vehicles/civ.md'
  - Version 3.0:
    - Home: '3.0/index.md'
    - Changelog: '3.0/changelog.md'
  

