version: 2
jobs:
  build:
    docker:
      - image: python:3.9
    steps:
       - checkout
       - run:
          name: Register Python alias for compatibility
          command: alias python='python3'
       - run:
          name: Install Python dependencies
          command: python3 -m pip install --upgrade -r requirements.txt
  docs-deploy:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Register Python alias for compatibility
          command: alias python='python3'
      - run:
          name: Install Python dependencies
          command: python3 -m pip install --upgrade -r requirements.txt
      - add_ssh_keys:
          fingerprints:
              - "SHA256:XQmDS6cMApIclvImbGm+BpMWfRGHKm809bjgx63E3Uw"
              - "SHA256:CIFVblCFM3FsNTtha6DvIrX0mEgO2qp/yneBnkjoYvA"
              - "SHA256:xguyZq0Tbs109QfREP2Ulm51Nx2cKM4itg7S0epyRQg"
              - "SHA256:Ziubt3UHmcRZkZ4PoZcMEQdXhthimezX74j3IECGLNo"
      - run:
          name: Deploy docs
          command: |
            git config user.email 25397933+Tslimshady99@users.noreply.github.com
            python3 -m mkdocs gh-deploy
workflows:
  version: 2
  build:
    jobs:
      - hold:
          type: approval
      - build:
          requires:
            - hold
      - docs-deploy:
          requires:
            - build