version: 2
jobs:
  build:
    docker:
      - image: python:3.9
    steps:
       - checkout
       - run:
          name: Register Python alias for compatibility
          command: alias python='python3'
       - run:
          name: Install Python dependencies
          command: python3 -m pip install --upgrade -r requirements.txt
  docs-deploy:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Register Python alias for compatibility
          command: alias python='python3'
      - run:
          name: Install Python dependencies
          command: python3 -m pip install --upgrade -r requirements.txt
      - add_ssh_keys:
          fingerprints:
              - "7a:1f:e1:32:bd:7e:9a:b8:81:b8:13:07:f6:44:2f:83"
      - run:
          name: Deploy docs
          command: |
            git config user.email 25397933+Tslimshady99@users.noreply.github.com
            python3 -m mkdocs gh-deploy
workflows:
  version: 2
  build:
    jobs:
      - hold:
          type: approval
      - build:
          requires:
            - hold
      - docs-deploy:
          requires:
            - build